### ISSUE TITLE
after install and try https visit in chrome , got a ERR_CONNECTION_CLOSED error, but http works

### ISSUE THREAD

**Issue by liuyang993** [opentok/opentok-rtc#518]
hi 

just as title say ,  seem only in https mode , chrome allow video and audio trans , but in my case , when I visit http://IP:8123 ,  it works , when change to https://IP:8123,  it not works , and got this error : ERR_CONNECTION_CLOSED  

Does me setting something wrong ?

**Comment by PeraDev7** [comment]
same thing
