### ISSUE TITLE
CycleVideo Bug Ios

### ISSUE THREAD

**Issue by SaadMansoor95** [opentok/opentok-rtc#601]
The cycleVideo function does not work on Ios iPhone. We are unable to switch camera. 
![Image from iOS](https://user-images.githubusercontent.com/57176668/83152514-5627f380-a117-11ea-976b-b1aa44b3e751.png)

**Comment by rhainer** [comment]
This works for me using Safari on iOS 13.3.1 using freeconferencing.vonage.com which is built from this repo. Can you provide some more information about your device and browser and how you are implementing this?

**Comment by msach22** [comment]
There was a regression with cycleVideo on Safari with JS 2.17.2. We are fixing this with 2.17.3 which should be out shortly.

**Comment by msach22** [comment]
OpenTok JS 2.17.3 was released yesterday - this issue can be closed!
