### ISSUE TITLE
Q: Scalable Video 

### ISSUE THREAD

**Issue by abdullah** [opentok/opentok-rtc#633]
👋  Hello, 

Before I start, I can not find a repository to post my question... Sorry about that.

We are building a video-call app for large groups. As OT documentation mentioned, to increase the quality and experience suggested approach is scalable video. The documentation says; When you use `vp8` with `chrome or safari` you will be able to use the scalable-video feature by calling the `setPreferredResolution`. We have experienced an unexpected behavior; when we call the `setPreferredResolution` function through the  `subscriber` the desired resolution applied between `2 seconds or 40 seconds or never`. We did not expect from the OT Media Router to reduce the video size exactly what we desired. It fits the best option and its ok. But, as I mentioned sometimes it increases the quality of` 1080x720` even we set the quality as `320x180` with `setPreferredResolution` function of `subscriber`.

Here is the sample code pieces to help us;

How we get the camera and microphone;

```
export const createMicrophoneAndCameraTracks = (options = {}) => {
  return new Promise((resolve, reject) => {
    const publisher = OT.initPublisher(null, {
      insertDefaultUI: false,
      publishVideo: true,
      publishAudio: true,
      width: 1280,
      height: 720,
      ...options,
    });

    publisher.on({
      accessDenied: reject,
      videoElementCreated: () => { return resolve(publisher); },
    });
  });
};
```

How we subscribe to a stream;
```
 session.subscribe(stream, null, {
      insertDefaultUI: false,
      preferredResolution: { width: 160, height: 90 },
    });
// rest of bussines logic
```

How we set the who has high-quality video or not

```
async selectStream(streamId) {
  this.selectedStreamId = streamId;

    session.streams.forEach((stream) => {
      const [subscriber] = session.getSubscribersForStream(stream);

      if (!subscriber) return;

      if (stream.streamId === streamId) {
        subscriber.setPreferredResolution(null);
      } else {
        subscriber.setPreferredResolution({ width: 160, height: 90 });
      }
    });
},
```

We think there is no problem with the code. We actually expect instant change (increasing or increasing.) in video quality when we call the `setPreferredResolution`.

Also, the [article](https://support.tokbox.com/hc/en-us/articles/360029733831-TokBox-Scalable-Video-Simulcast-FAQ) by opentok says 

> Note that Scalable Video is a publisher's property. Default platform behavior is designed to avoid the use of Simulcast for 1-1 (1-participant) calls. So a publisher will publish in Simulcast only if there are >2 connections in the sessions.

but there is no information about that in the documentation. This is valid?

Thanks for your all answers.

**Comment by rhainer** [comment]
Yes, that comment about Scalable Video only being enabled in multi-party calls is valid. SV adds no value in 1-1 to call as the publisher and subscriber will negotiate an appropriate frame rate and resolution without it. For your other questions, I recommend you contact the Vonage video technical support team at https://support.tokbox.com/hc/en-us

**Comment by abdullah** [comment]
Thank you. I will open a ticket 👍
